#!/bin/bash

[ "$1" == "on" ] && xinput enable $(xinput list --short | grep TrackPoint | grep -oP "id=\K..") && echo TrackPoint Enabled

[ "$1" == "off" ] && xinput disable $(xinput list --short | grep TrackPoint | grep -oP "id=\K..") && echo TrackPoint Disabled

if [ -z "$1" ]; then
  while true; do trackpoint off; sleep 300; done
fi

exit 0


